---

- hosts: all
  become: true
  tasks:
          - name: update ubuntu repository index
            apt:
                    update_cache: yes
            when: ansible_distribution == 'Ubuntu'

          - name: install apache2 package
            apt:
                    name: apache2
                    state: latest
            when: ansible_distribution == 'Ubuntu'        

          - name: add php support for apache2
            apt:
                    name: libapache2-mod-php
                    state: latest
            when: ansible_distribution == 'Ubuntu'

          - name: update redhat repository index
            yum:
                    update_cache: yes
            when: ansible_distribution == 'RedHat'

          - name: install httpd package
            yum:
                    name: httpd
                    state: latest
            when: ansible_distribution == 'RedHat'

          - name: install php support for httpd
            yum:
                    name: php
                    state: latest
            when: ansible_distribution == 'RedHat'         
