---

- hosts: all
  become: true
  pre_tasks:
          - name: install updates (RedHat)
            tags: always
            yum:
                    update_only: yes
                    update_cache: yes
            when: ansible_distribution == 'RedHat'

          - name: install updates (Ubuntu)
            tags: always
            apt:
                    upgrade: dist
                    update_cache: yes
            when: ansible_distribution == 'Ubuntu'

- hosts: workstations
  become: true
  tasks:
           - name: install unzip
             package:
                     name: unzip

           - name: install terraform
             unarchive:
                     src: https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
                     dest: /usr/local/bin
                     remote_src: yes
                     mode: 0755
                     owner: root
                     group: root

- hosts: web_servers
  become: true
  tasks:  
          - name: install apache2 and php packages for ubuntu
            tags: apache,apache2,ubuntu
            apt:
                    name: 
                      - apache2
                      - libapache2-mod-php
                    state: latest
            when: ansible_distribution == 'Ubuntu'        

          - name: install httpd pnd php packages for redhat
            tags: apache,httpd,redhat
            yum:
                    name: 
                       - httpd
                       - php
                    state: latest
            when: ansible_distribution == 'RedHat'

          - name: copy html file for site
            tags: apache,apache2,httpd
            copy:
                    src: default_site.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644

- hosts: db_servers
  become: true
  tasks:
          - name: install mariadb server package (RedHat)
            tags: db,mariadb,redhat
            yum:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == 'RedHat'

          - name: install mariadb server package (Ubuntu)
            tags: db,mariadb,ubuntu
            apt:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == 'Ubuntu'

- hosts: file_servers
  become: true
  tasks:
          - name: install samba package
            tags: samba
            package:
                    name: samba
                    state: latest  
