---

- hosts: all
  become: true
  pre_tasks:
          - name: install updates (RedHat)
            yum:
                    update_only: yes
                    update_cache: yes
            when: ansible_distribution == 'RedHat'

          - name: install updates (Ubuntu)
            apt:
                    upgrade: dist
                    update_cache: yes
            when: ansible_distribution == 'Ubuntu'
            
- hosts: web_servers
  become: true
  tasks:  
          - name: install apache2 and php packages for ubuntu
            apt:
                    name: 
                      - apache2
                      - libapache2-mod-php
                    state: latest
            when: ansible_distribution == 'Ubuntu'        

          - name: install httpd pnd php packages for redhat
            yum:
                    name: 
                       - httpd
                       - php
                    state: latest
            when: ansible_distribution == 'RedHat'

- hosts: db_servers
  become: true
  tasks:
          - name: install mariadb server package (RedHat)
            yum:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == 'RedHat'

          - name: install mariadb server package (Ubuntu)
            apt:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == 'Ubuntu'

- hosts: file_servers
  become: true
  tasks:
          - name: install samba package
            package:
                    name: samba
                    state: latest  
